
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speechess
tts:
  - platform: google_translate

frontend:
  extra_module_url:
    - /hacsfiles/button-card/button-card.js
    - /hacsfiles/light-entity-card/light-entity-card.js
    - /hacsfiles/lovelace-mushroom/mushroom.js
    - /hacsfiles/my-cards-slider-card/my-cards.js
    - /hacsfiles/button-card/button-card.js
    - /hacsfiles/lovelace-auto-entities/auto-entities.js
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    - /hacsfiles/mini-media-player/mini-media-player-bundle.js

   # - /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
   # - /hacsfiles/lovelace-hui-element/hui-element.js
#    - /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
#type: module
#    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

# Example configuration.yaml entry
alert:
  front_door:
    name: Front door is open
    done_message: Front door is closed
    entity_id: binary_sensor.frontdoorsensor
    state: "on"
    repeat: 30
    can_acknowledge: true
    skip_first: true
    notifiers:
      - paosin_iphone12_pro
  deck_door:
    name: Deck door is open
    done_message: Deck door is closed
    entity_id: binary_sensor.deck_door
    state: "on"
    repeat: 30
    can_acknowledge: true
    skip_first: true
    notifiers:
      - paosin_iphone12_pro


lovelace:
  mode: storage
  # Add yaml dashboards
#  dashboards:
#    lovelace-yaml:
#      mode: yaml
#      title: Minimalist
#      icon: mdi:script
#      show_in_sidebar: true
#      filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml
  #resources:
  #  - url: /local/mini-media-player-bundle.js?v=1.16.2
  #    type: module
#  resources:
#    - url: /hacsfiles/lovelace-mushroom/mushroom.js
#      type: module
#    - url: /hacsfiles/mini-media-player-bundle.js?v=1.16.2
#      type: module
#    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
#      type: module
#    - url: /hacsfiles/my-cards-slider-card/my-cards/my-cards.js
#      type: module      
      
# Example configuration.yaml entry
mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  include:
    domains:
      - alarm_control_panel
      - light
      - person
      - switch
      - sensor
      - fan
      - virtual
      - button
      - binary_sensor
      - remote
      - lock
      - vacuum
      - input_boolean
  exclude:
    entity_globs:
      - sensor.*_node_status*
      - sensor.paosin_*
      - sensor.epson_*
      - sensor.femi_s_*
      - sensor.hacs
      - button.*_ping
      - sensor.*_electric*
      - sensor.*_scene_*
      #- binary_sensor.*
      
      #- binary_sensor.*
#      - binary_sensor.*_occupancy
#lovelace:
#  mode: yaml
  
virtual:

switch:
  - platform: virtual
    name: TV
  - platform: virtual
    name: Office Control
  - platform: virtual
    name: Femi Presence
  - platform: virtual
    name: Good Night
  - platform: virtual
    name: Man Cave
#fan:
#  - platform: virtual
#    name: Master Bedroom Fan
#    speed: True
#    speed_count: 4
#    direction: True
#    oscillate: True
#    initial_availability: true
nest:
  client_id: 673989526747-j0la40jj1cv9u99psq7pp9mnabcom0mk.apps.googleusercontent.com
  client_secret: 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
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: 052fef06-ba68-4fed-9c4f-e3e34e26dda4
        
homeassistant:
  packages: !include_dir_named packages

      
homekit:
  - filter:
      include_domains:
        - light
        - switch
        - fan
        - thermostat
#      include_entity_globs:
#        - binary_sensor.*_occupancy
    entity_config:
      switch.basement_stairs_lights:
        type: outlet

logger:
  default: info
  logs:
    homeassistant.components.samsungtv: debug
    samsungctl: debug
#light:
#  - platform: decora_wifi
#    username: femiosinowo@gmail.com
#    password: P@ssw0rd
    
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
